### ISSUE TITLE
[BUG] compiler crash using go 1.6.x

### ISSUE THREAD

**Issue by PureWhiteWu** [google/go-jsonnet#177]
hi, it's me again and again....

## how to reproduce
I tried to compile jsonnet on a brand new vm on gce, using the ubuntu 16.04 and n1-highcpu-2（2  vCPU,1.8 GB）
I downloaded the go binary from https://dl.google.com/go/go1.6.4.linux-amd64.tar.gz and install following the instruction at https://golang.org/doc/install.
And i executed `go get -u github.com/fatih/color`, then `go build`.

![image](https://user-images.githubusercontent.com/3314335/34975848-bdaee99c-face-11e7-8468-99b1e40ab3a7.png)

![image](https://user-images.githubusercontent.com/3314335/34975855-c3ae8654-face-11e7-9655-5d9275b585a2.png)

![image](https://user-images.githubusercontent.com/3314335/34975862-cae5106e-face-11e7-84b1-2790d6ccdecf.png)

**Comment by PureWhiteWu** [comment]
go 1.7.0 also encountered error:
```
daniel@instance-1:~/go/src/github.com/google/go-jsonnet/jsonnet$ go build
# github.com/google/go-jsonnet/ast
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x900de8, 0x16)
	/usr/local/go/src/runtime/panic.go:566 +0x95
runtime.sysMap(0xc4633b0000, 0x22ff0000, 0x7f08aba65e00, 0xb67898)
	/usr/local/go/src/runtime/mem_linux.go:219 +0x1d0
runtime.(*mheap).sysAlloc(0xb45e40, 0x22ff0000, 0x7f0800000001)
	/usr/local/go/src/runtime/malloc.go:407 +0x37a
runtime.(*mheap).grow(0xb45e40, 0x117f5, 0x0)
	/usr/local/go/src/runtime/mheap.go:726 +0x62
runtime.(*mheap).allocSpanLocked(0xb45e40, 0x117f5, 0x2000)
	/usr/local/go/src/runtime/mheap.go:630 +0x4f2
runtime.(*mheap).alloc_m(0xb45e40, 0x117f5, 0x7f0100000000, 0x7fffb85093d8)
	/usr/local/go/src/runtime/mheap.go:515 +0xe0
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:579 +0x4b
runtime.systemstack(0x7fffb85093e0)
	/usr/local/go/src/runtime/asm_amd64.s:314 +0xab
runtime.(*mheap).alloc(0xb45e40, 0x117f5, 0x10100000000, 0x2)
	/usr/local/go/src/runtime/mheap.go:580 +0x73
runtime.largeAlloc(0x22fe81a0, 0x7f08ad3a5001, 0x7f0800000002)
	/usr/local/go/src/runtime/malloc.go:774 +0x93
runtime.mallocgc.func1()
	/usr/local/go/src/runtime/malloc.go:669 +0x3e
runtime.systemstack(0xb34000)
	/usr/local/go/src/runtime/asm_amd64.s:298 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1079

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:252 fp=0xc4561a50e0 sp=0xc4561a50d8
runtime.mallocgc(0x22fe81a0, 0x8a63e0, 0x201, 0xc4561a51c8)
	/usr/local/go/src/runtime/malloc.go:670 +0x903 fp=0xc4561a5180 sp=0xc4561a50e0
runtime.makeslice(0x8a63e0, 0x8bfa068, 0x8bfa068, 0xb34700, 0x1007f08ad3a5000, 0x0)
	/usr/local/go/src/runtime/slice.go:57 +0x7b fp=0xc4561a51d8 sp=0xc4561a5180
cmd/compile/internal/gc.newliveness(0xc428de03f0, 0xc4201b5758, 0xc463018000, 0x109ee, 0x12c00, 0xc463346000, 0x2666, 0x3000, 0x2667)
	/usr/local/go/src/cmd/compile/internal/gc/plive.go:693 +0x15e fp=0xc4561a5360 sp=0xc4561a51d8
cmd/compile/internal/gc.liveness(0xc428de03f0, 0xc4201b5758, 0xc4498a2a80, 0xc4498a2af0)
	/usr/local/go/src/cmd/compile/internal/gc/plive.go:1736 +0x1fc fp=0xc4561a5408 sp=0xc4561a5360
cmd/compile/internal/gc.genssa(0xc4203b00f0, 0xc4201b5758, 0xc4498a2a80, 0xc4498a2af0)
	/usr/local/go/src/cmd/compile/internal/gc/ssa.go:4057 +0xae6 fp=0xc4561a56f8 sp=0xc4561a5408
cmd/compile/internal/gc.compile(0xc428de03f0)
	/usr/local/go/src/cmd/compile/internal/gc/pgen.go:482 +0x75a fp=0xc4561a59a8 sp=0xc4561a56f8
cmd/compile/internal/gc.funccompile(0xc428de03f0)
	/usr/local/go/src/cmd/compile/internal/gc/dcl.go:1287 +0x186 fp=0xc4561a5a20 sp=0xc4561a59a8
cmd/compile/internal/gc.fninit(0xc42049a000, 0x699, 0x6a0)
	/usr/local/go/src/cmd/compile/internal/gc/init.go:182 +0xb90 fp=0xc4561a5b98 sp=0xc4561a5a20
cmd/compile/internal/gc.Main()
	/usr/local/go/src/cmd/compile/internal/gc/main.go:472 +0x1ba1 fp=0xc4561a5de0 sp=0xc4561a5b98
cmd/compile/internal/amd64.Main()
	/usr/local/go/src/cmd/compile/internal/amd64/galign.go:93 +0x2fa fp=0xc4561a5e18 sp=0xc4561a5de0
main.main()
	/usr/local/go/src/cmd/compile/main.go:33 +0x2a3 fp=0xc4561a5ea8 sp=0xc4561a5e18
runtime.main()
	/usr/local/go/src/runtime/proc.go:183 +0x1f4 fp=0xc4561a5f00 sp=0xc4561a5ea8
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4561a5f08 sp=0xc4561a5f00
```

**Comment by sbarzowski** [comment]
Huh, this is not a compile error. It is an ICE - compiler crash.

**Comment by PureWhiteWu** [comment]
I've tested go 1.8 and go 1.9.2, and they works fine.

**Comment by PureWhiteWu** [comment]
![image](https://user-images.githubusercontent.com/3314335/34976412-866c75fa-fad1-11e7-8350-8e98a37765ae.png)

So is this a bug of the compiler or some of jsonnet code?

**Comment by PureWhiteWu** [comment]
also crashes on 1.7.4:
```
daniel@instance-1:~$ wget https://dl.google.com/go/go1.7.4.linux-amd64.tar.gz
--2018-01-16 07:26:51--  https://dl.google.com/go/go1.7.4.linux-amd64.tar.gz
Resolving dl.google.com (dl.google.com)... 74.125.24.93, 74.125.24.91, 74.125.24.136, ...
Connecting to dl.google.com (dl.google.com)|74.125.24.93|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 84021919 (80M) [application/x-gzip]
Saving to: ‘go1.7.4.linux-amd64.tar.gz’

go1.7.4.linux-amd64.tar.gz                                 100%[========================================================================================================================================>]  80.13M  30.6MB/s    in 2.6s

2018-01-16 07:26:54 (30.6 MB/s) - ‘go1.7.4.linux-amd64.tar.gz’ saved [84021919/84021919]

daniel@instance-1:~$ sudo rm -rf /usr/local/go
daniel@instance-1:~$ sudo tar -C /usr/local -xzf go1.7.4.linux-amd64.tar.gz
daniel@instance-1:~$ go version
go version go1.7.4 linux/amd64
daniel@instance-1:~$ cd go/src/github.com/google/go-jsonnet/jsonnet/
daniel@instance-1:~/go/src/github.com/google/go-jsonnet/jsonnet$ go build
# github.com/google/go-jsonnet/ast
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x900e01, 0x16)
	/usr/local/go/src/runtime/panic.go:566 +0x95
runtime.sysMap(0xc45fb50000, 0x22ff0000, 0x7f1a5ec52300, 0xb67898)
	/usr/local/go/src/runtime/mem_linux.go:219 +0x1d0
runtime.(*mheap).sysAlloc(0xb45e40, 0x22ff0000, 0x7f1a00000001)
	/usr/local/go/src/runtime/malloc.go:407 +0x37a
runtime.(*mheap).grow(0xb45e40, 0x117f5, 0x0)
	/usr/local/go/src/runtime/mheap.go:726 +0x62
runtime.(*mheap).allocSpanLocked(0xb45e40, 0x117f5, 0x2000)
	/usr/local/go/src/runtime/mheap.go:630 +0x4f2
runtime.(*mheap).alloc_m(0xb45e40, 0x117f5, 0x100000000, 0xc420039ec8)
	/usr/local/go/src/runtime/mheap.go:515 +0xe0
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:579 +0x4b
runtime.systemstack(0xc420039ed0)
	/usr/local/go/src/runtime/asm_amd64.s:314 +0xab
runtime.(*mheap).alloc(0xb45e40, 0x117f5, 0x10100000000, 0x2)
	/usr/local/go/src/runtime/mheap.go:580 +0x73
runtime.largeAlloc(0x22fe81a0, 0x7f1a60578001, 0x7f1a00000002)
	/usr/local/go/src/runtime/malloc.go:774 +0x93
runtime.mallocgc.func1()
	/usr/local/go/src/runtime/malloc.go:669 +0x3e
runtime.systemstack(0xc42001a000)
	/usr/local/go/src/runtime/asm_amd64.s:298 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1079

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:252 fp=0xc457e150f0 sp=0xc457e150e8
runtime.mallocgc(0x22fe81a0, 0x8a63e0, 0x201, 0xc457e151d8)
	/usr/local/go/src/runtime/malloc.go:670 +0x903 fp=0xc457e15190 sp=0xc457e150f0
runtime.makeslice(0x8a63e0, 0x8bfa068, 0x8bfa068, 0xc420410400, 0x1007f1a60578000, 0x0)
	/usr/local/go/src/runtime/slice.go:57 +0x7b fp=0xc457e151e8 sp=0xc457e15190
cmd/compile/internal/gc.newliveness(0xc42a42a900, 0xc42019b758, 0xc45f77a000, 0x109ee, 0x12c00, 0xc45faa8000, 0x2666, 0x3000, 0x2667)
	/usr/local/go/src/cmd/compile/internal/gc/plive.go:693 +0x15e fp=0xc457e15370 sp=0xc457e151e8
cmd/compile/internal/gc.liveness(0xc42a42a900, 0xc42019b758, 0xc44b13aa80, 0xc44b13aaf0)
	/usr/local/go/src/cmd/compile/internal/gc/plive.go:1736 +0x1fc fp=0xc457e15418 sp=0xc457e15370
cmd/compile/internal/gc.genssa(0xc4203980f0, 0xc42019b758, 0xc44b13aa80, 0xc44b13aaf0)
	/usr/local/go/src/cmd/compile/internal/gc/ssa.go:4057 +0xae6 fp=0xc457e15708 sp=0xc457e15418
cmd/compile/internal/gc.compile(0xc42a42a900)
	/usr/local/go/src/cmd/compile/internal/gc/pgen.go:482 +0x75a fp=0xc457e159b8 sp=0xc457e15708
cmd/compile/internal/gc.funccompile(0xc42a42a900)
	/usr/local/go/src/cmd/compile/internal/gc/dcl.go:1287 +0x186 fp=0xc457e15a30 sp=0xc457e159b8
cmd/compile/internal/gc.fninit(0xc420086000, 0x699, 0x6a0)
	/usr/local/go/src/cmd/compile/internal/gc/init.go:182 +0xb90 fp=0xc457e15ba8 sp=0xc457e15a30
cmd/compile/internal/gc.Main()
	/usr/local/go/src/cmd/compile/internal/gc/main.go:472 +0x1ba1 fp=0xc457e15df0 sp=0xc457e15ba8
cmd/compile/internal/amd64.Main()
	/usr/local/go/src/cmd/compile/internal/amd64/galign.go:93 +0x2fa fp=0xc457e15e28 sp=0xc457e15df0
main.main()
	/usr/local/go/src/cmd/compile/main.go:33 +0x2a3 fp=0xc457e15eb8 sp=0xc457e15e28
runtime.main()
	/usr/local/go/src/runtime/proc.go:183 +0x1f4 fp=0xc457e15f10 sp=0xc457e15eb8
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc457e15f18 sp=0xc457e15f10
daniel@instance-1:~/go/src/github.com/google/go-jsonnet/jsonnet$ free -m
              total        used        free      shared  buff/cache   available
Mem:           1790         119        1290           2         380        1492
Swap:             0           0           0
daniel@instance-1:~/go/src/github.com/google/go-jsonnet/jsonnet$
```

**Comment by PureWhiteWu** [comment]
I tested on a larger vm, and it turns out that there may be a bug in go 1.6 compiler so it's not able to compile using 1.6, but 1.7.0 and 1.7.6 works fine.
```
daniel@instance-2:~$ sudo tar -C /usr/local -xzf go1.6.4.linux-amd64.tar.gz
daniel@instance-2:~$ export PATH=$PATH:/usr/local/go/bin
daniel@instance-2:~$ mkdir -p go/src/github.com/google
daniel@instance-2:~$ cd go/src/github.com/google/
daniel@instance-2:~/go/src/github.com/google$ git clone https://github.com/google/go-jsonnet.git
Cloning into 'go-jsonnet'...
remote: Counting objects: 1839, done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 1839 (delta 6), reused 19 (delta 3), pack-reused 1802
Receiving objects: 100% (1839/1839), 5.28 MiB | 1.51 MiB/s, done.
Resolving deltas: 100% (698/698), done.
Checking connectivity... done.
daniel@instance-2:~/go/src/github.com/google$ cd go-jsonnet/
daniel@instance-2:~/go/src/github.com/google/go-jsonnet$ ls
ast          compat        desugarer.go       dump                imports.go           jsonnet          linter                             parser              runtime_error.go         std                   tests.sh   vm.go
builtins.go  compat_test   desugarer_test.go  error_formatter.go  interpreter.go       jsonnet_test.go  main_test.go                       README.md           static_analyzer.go       std.thisFile.jsonnet  thunks.go
cmd          CONTRIBUTING  doc.go             evaluator.go        interpreter_test.go  LICENSE          mutually_recursive_defaults.input  reset_stdast_go.sh  static_analyzer_test.go  testdata              value.go
daniel@instance-2:~/go/src/github.com/google/go-jsonnet$ pwd
/home/daniel/go/src/github.com/google/go-jsonnet
daniel@instance-2:~/go/src/github.com/google/go-jsonnet$ ls
ast          compat        desugarer.go       dump                imports.go           jsonnet          linter                             parser              runtime_error.go         std                   tests.sh   vm.go
builtins.go  compat_test   desugarer_test.go  error_formatter.go  interpreter.go       jsonnet_test.go  main_test.go                       README.md           static_analyzer.go       std.thisFile.jsonnet  thunks.go
cmd          CONTRIBUTING  doc.go             evaluator.go        interpreter_test.go  LICENSE          mutually_recursive_defaults.input  reset_stdast_go.sh  static_analyzer_test.go  testdata              value.go
daniel@instance-2:~/go/src/github.com/google/go-jsonnet$ pwd
/home/daniel/go/src/github.com/google/go-jsonnet
daniel@instance-2:~/go/src/github.com/google/go-jsonnet$ cd jsonnet/
daniel@instance-2:~/go/src/github.com/google/go-jsonnet/jsonnet$ go build
cmd.go:31:2: cannot find package "github.com/fatih/color" in any of:
	/usr/local/go/src/github.com/fatih/color (from $GOROOT)
	($GOPATH not set)
cmd.go:32:2: cannot find package "github.com/google/go-jsonnet" in any of:
	/usr/local/go/src/github.com/google/go-jsonnet (from $GOROOT)
	($GOPATH not set)
daniel@instance-2:~/go/src/github.com/google/go-jsonnet/jsonnet$ go get -u github.com/fatih/color
package github.com/fatih/color: cannot download, $GOPATH not set. For more details see: go help gopath
daniel@instance-2:~/go/src/github.com/google/go-jsonnet/jsonnet$ export GOPATH=$HOME/go
daniel@instance-2:~/go/src/github.com/google/go-jsonnet/jsonnet$ go get -u github.com/fatih/color
daniel@instance-2:~/go/src/github.com/google/go-jsonnet/jsonnet$ go build
# github.com/google/go-jsonnet/ast
panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
panic(0x803ba0, 0xc84dd40b70)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
cmd/compile/internal/gc.newliveness(0xc82a2626c0, 0xc82af6cfc0, 0xc8518a6000, 0x3cd44, 0x48800, 0xc851ee4000, 0xd09c, 0xf000, 0x9869ac5bda4f6ea8)
	/usr/local/go/src/cmd/compile/internal/gc/plive.go:687 +0x161
cmd/compile/internal/gc.liveness(0xc82a2626c0, 0xc82af6cfc0, 0xc833fc9380, 0xc833fc9400)
	/usr/local/go/src/cmd/compile/internal/gc/plive.go:1782 +0x2cf
cmd/compile/internal/gc.compile(0xc82a2626c0)
	/usr/local/go/src/cmd/compile/internal/gc/pgen.go:541 +0xdf2
cmd/compile/internal/gc.funccompile(0xc82a2626c0)
	/usr/local/go/src/cmd/compile/internal/gc/dcl.go:1450 +0x1c0
cmd/compile/internal/gc.fninit(0xc82293c4a0)
	/usr/local/go/src/cmd/compile/internal/gc/init.go:184 +0x8a4
cmd/compile/internal/gc.Main()
	/usr/local/go/src/cmd/compile/internal/gc/lex.go:477 +0x2150
cmd/compile/internal/amd64.Main()
	/usr/local/go/src/cmd/compile/internal/amd64/galign.go:127 +0x58d
main.main()
	/usr/local/go/src/cmd/compile/main.go:32 +0x395
daniel@instance-2:~/go/src/github.com/google/go-jsonnet/jsonnet$ cd
daniel@instance-2:~$ https://dl.google.com/go/go1.7.6.linux-amd64.tar.gz
-bash: https://dl.google.com/go/go1.7.6.linux-amd64.tar.gz: No such file or directory
daniel@instance-2:~$ wget https://dl.google.com/go/go1.7.6.linux-amd64.tar.gz
--2018-01-16 07:35:25--  https://dl.google.com/go/go1.7.6.linux-amd64.tar.gz
Resolving dl.google.com (dl.google.com)... 74.125.68.91, 74.125.68.93, 74.125.68.190, ...
Connecting to dl.google.com (dl.google.com)|74.125.68.91|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 84237339 (80M) [application/x-gzip]
Saving to: ‘go1.7.6.linux-amd64.tar.gz’

go1.7.6.linux-amd64.tar.gz                                 100%[========================================================================================================================================>]  80.33M   221MB/s    in 0.4s

2018-01-16 07:35:25 (221 MB/s) - ‘go1.7.6.linux-amd64.tar.gz’ saved [84237339/84237339]

daniel@instance-2:~$ sudo rm -rf /usr/local/go/
daniel@instance-2:~$ sudo tar -C /usr/local -xzf go1.7.6.linux-amd64.tar.gz
daniel@instance-2:~$ go version
go version go1.7.6 linux/amd64
daniel@instance-2:~$ cd go/src/github.com/google/go-jsonnet/jsonnet/
daniel@instance-2:~/go/src/github.com/google/go-jsonnet/jsonnet$ go build
daniel@instance-2:~/go/src/github.com/google/go-jsonnet/jsonnet$ free -m
              total        used        free      shared  buff/cache   available
Mem:          15032         155       13973           8         903       14556
Swap:             0           0           0
daniel@instance-2:~/go/src/github.com/google/go-jsonnet/jsonnet$ cd
daniel@instance-2:~$ sudo rm -rf /usr/local/go/
daniel@instance-2:~$ wget https://dl.google.com/go/go1.7.linux-amd64.tar.gz
--2018-01-16 07:37:09--  https://dl.google.com/go/go1.7.linux-amd64.tar.gz
Resolving dl.google.com (dl.google.com)... 74.125.200.93, 74.125.200.190, 74.125.200.136, ...
Connecting to dl.google.com (dl.google.com)|74.125.200.93|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 81573766 (78M) [application/x-gzip]
Saving to: ‘go1.7.linux-amd64.tar.gz’

go1.7.linux-amd64.tar.gz                                   100%[========================================================================================================================================>]  77.79M  37.3MB/s    in 2.1s

2018-01-16 07:37:12 (37.3 MB/s) - ‘go1.7.linux-amd64.tar.gz’ saved [81573766/81573766]

daniel@instance-2:~$ sudo tar -C /usr/local -xzf go1.7.linux-amd64.tar.gz
daniel@instance-2:~$ cd go/src/github.com/google/go-jsonnet/jsonnet/
daniel@instance-2:~/go/src/github.com/google/go-jsonnet/jsonnet$ go build
daniel@instance-2:~/go/src/github.com/google/go-jsonnet/jsonnet$ free -m
              total        used        free      shared  buff/cache   available
Mem:          15032         157       13893           8         981       14552
Swap:             0           0           0
daniel@instance-2:~/go/src/github.com/google/go-jsonnet/jsonnet$
```

**Comment by sbarzowski** [comment]
Well, Go compiler shouldn't crash under any circumstances.

That said it crashes on a pretty weird file - pregenerated stdlib AST, so it's very likely that something there is bigger than what compiler authors considered reasonable.

I would just raise the "known to work" version of the compiler to go1.8 - especially since some of our dependencies test only go1.8 too at the moment. Do you have any particular reason to stick to Go 1.6/1.7?

Many thanks for the report!

**Comment by PureWhiteWu** [comment]
I need to use this on go 1.7 for some compatibility reasons, but I think it's okay to compile this on a machine with more than 4GB mem. 
I think raising the "known to work" version to 1.8 makes sense, since in most cases users do not need to use version earlier than 1.8.

**Comment by PureWhiteWu** [comment]
I think the problem is not the stdlib's ast, it's the go-jsonnet's ast.
`# github.com/google/go-jsonnet/ast`
@sbarzowski

**Comment by sbarzowski** [comment]
Yeah, I noticed that. Go compiler crashes when it analyzes go-jsonnet ast, most likely the autogenerated part (`stdast.go`).

**Comment by PureWhiteWu** [comment]
oh, okay. thanks
