### ISSUE TITLE
INTERNAL ERROR: (CRASH) Unexpected node 

### ISSUE THREAD

**Issue by dan-compton** [google/go-jsonnet#255]
Here's something I ran across while trawling for solutions to [this question] (https://groups.google.com/forum/#!topic/jsonnet/SFjTwXgZEr0) that do not involve using go to walk, manipulate, and dump the AST to jsonnet source code as I currently do.

```
[1] dc@boring-banao> jsonnet -e '(import "experiment.jsonnet") + {a: "asdf"}'

INTERNAL ERROR: (CRASH) Unexpected node &ast.Dollar{NodeBase:ast.NodeBase{loc:ast.LocationRange{FileName:"experiment.jsonnet", Begin:ast.Location{Line:8, Column:1}, End:ast.Location{Line:8, Column:2}, file:(*ast.Source)(0xc00000ac40)}, context:(ast.Context)(0x6fcc50), freeVariables:ast.Identifiers{}}}
goroutine 1 [running]:
runtime/debug.Stack(0xc0001ad3d8, 0x546a60, 0xc000051180)
	/home/dc/.gvm/gos/go1.11/src/runtime/debug/stack.go:24 +0xa7
github.com/google/go-jsonnet.(*VM).evaluateSnippet.func1(0xc0001afae8)
	/home/dc/work/src/github.com/google/go-jsonnet/vm.go:102 +0x6e
panic(0x546a60, 0xc000051180)
	/home/dc/.gvm/gos/go1.11/src/runtime/panic.go:513 +0x1b9
github.com/google/go-jsonnet.analyzeVisit(0x5d7640, 0xc00005e300, 0x0, 0xc00000f230, 0x0, 0x0)
	/home/dc/work/src/github.com/google/go-jsonnet/static_analyzer.go:146 +0x1ce9
github.com/google/go-jsonnet.visitNext(0x5d7640, 0xc00005e300, 0x0, 0xc00000f230, 0xc0001ade10)
	/home/dc/work/src/github.com/google/go-jsonnet/static_analyzer.go:35 +0x5b
github.com/google/go-jsonnet.analyzeVisit(0x5d7440, 0xc00009c140, 0x0, 0xc00000f230, 0x0, 0x0)
	/home/dc/work/src/github.com/google/go-jsonnet/static_analyzer.go:45 +0xff2
github.com/google/go-jsonnet.visitNext(0x5d7440, 0xc00009c140, 0xc000022100, 0xc00000f230, 0xc0001ae638)
	/home/dc/work/src/github.com/google/go-jsonnet/static_analyzer.go:35 +0x5b
github.com/google/go-jsonnet.analyzeVisit(0x5d7900, 0xc0000b8500, 0x0, 0xc00000f1d0, 0xc000051000, 0x0)
	/home/dc/work/src/github.com/google/go-jsonnet/static_analyzer.go:110 +0x91a
github.com/google/go-jsonnet.analyze(0x5d7900, 0xc0000b8500, 0x0, 0x5d7900)
	/home/dc/work/src/github.com/google/go-jsonnet/static_analyzer.go:153 +0x76
github.com/google/go-jsonnet.snippetToAST(0xc00001a420, 0x12, 0xc000022120, 0x59, 0xc000050fd0, 0x0, 0xc00001a420, 0x0)
	/home/dc/work/src/github.com/google/go-jsonnet/vm.go:180 +0x12b
github.com/google/go-jsonnet.codeToPV(0xc0000840a0, 0xc00001a420, 0x12, 0xc000022120, 0x59, 0xc000050f00)
	/home/dc/work/src/github.com/google/go-jsonnet/imports.go:110 +0x59
github.com/google/go-jsonnet.(*ImportCache).ImportCode(0xc00000a2e0, 0x57f783, 0x9, 0xc00001a420, 0x12, 0xc0000840a0, 0xc00005e180, 0x6fcc50, 0x7fc5ff6f9000, 0x8, ...)
	/home/dc/work/src/github.com/google/go-jsonnet/imports.go:136 +0x186
github.com/google/go-jsonnet.(*interpreter).evaluate(0xc0000840a0, 0x5d7700, 0xc00005e180, 0x1, 0x0, 0x5d7a00, 0xc00005e1e0, 0xc0001af3d8)
	/home/dc/work/src/github.com/google/go-jsonnet/interpreter.go:453 +0x2f5e
github.com/google/go-jsonnet.(*interpreter).evaluate(0xc0000840a0, 0x5d7580, 0xc0000b8180, 0x1, 0x0, 0x75bcd15, 0xc00000eea0, 0x0)
	/home/dc/work/src/github.com/google/go-jsonnet/interpreter.go:322 +0x2418
github.com/google/go-jsonnet.(*interpreter).EvalInCleanEnv(0xc0000840a0, 0xc00005a1c0, 0x0, 0xc0001af898, 0x5d7580, 0xc0000b8180, 0x75bcd00, 0xc00000eea0, 0x0, 0x0, ...)
	/home/dc/work/src/github.com/google/go-jsonnet/interpreter.go:904 +0xc7
github.com/google/go-jsonnet.evaluateAux(0xc0000840a0, 0x5d7580, 0xc0000b8180, 0xc00000ea50, 0xc00000a260, 0xc0000840a0, 0x0, 0x0, 0xc0000b8180, 0x0)
	/home/dc/work/src/github.com/google/go-jsonnet/interpreter.go:1171 +0x159
github.com/google/go-jsonnet.evaluate(0x5d7580, 0xc0000b8180, 0xc00000ea20, 0xc00000ea50, 0xc00000ea80, 0x1f4, 0x5d6aa0, 0xc00000a260, 0xc00004ba00, 0x40b30f, ...)
	/home/dc/work/src/github.com/google/go-jsonnet/interpreter.go:1207 +0xc1
github.com/google/go-jsonnet.(*VM).evaluateSnippet(0xc000084050, 0x57f783, 0x9, 0x7ffc918c198a, 0x2b, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/dc/work/src/github.com/google/go-jsonnet/vm.go:111 +0x32a
github.com/google/go-jsonnet.(*VM).EvaluateSnippet(0xc000084050, 0x57f783, 0x9, 0x7ffc918c198a, 0x2b, 0x0, 0x1, 0x0, 0x0)
	/home/dc/work/src/github.com/google/go-jsonnet/vm.go:133 +0x69
main.main()
	/home/dc/work/src/github.com/google/go-jsonnet/jsonnet/cmd.go:577 +0xdde

Please report a bug here: https://github.com/google/go-jsonnet/issues
```

And of course the offending code (experiment.jsonnet)
```
local A = {
    local b = 'asdf',
    s: b,
    q: "test",
    z: function(i) i
};

$(A) // dolla make go-jsonnet holla
```

**Comment by dan-compton** [comment]
It appears to be valid syntax.  $(A) is meaningless to me.  Is there any context wherein it would have meaning?

**Comment by dan-compton** [comment]
What I want to be able to do is read a jsonnet file, make modifications, and write it as sugared jsonnet as described in the google group post.  This was a happy accident.

**Comment by seh** [comment]
Can you correct the hyperlink above? It appears to point to a message in your own inbox.

**Comment by dan-compton** [comment]
Apologies @seh it's been corrected abov (https://groups.google.com/forum/#!topic/jsonnet/SFjTwXgZEr0)

I appreciate your help.

**Comment by seh** [comment]
I thought that `$(A)` might mean to invoke a top-level function with one parameter, supplying a value named "A" as the lone argument. However, my attempts thus far to construct a program that has such a top-level function that's addressable by `$` fail. Starting with a top-level function, `$` points to the result of evaluating that function, not the function itself.

**Comment by dan-compton** [comment]
That is clear, however I cannot think of a program that satisfies this.  It is very interesting.   Any input on the google-groups post.

**Comment by sbarzowski** [comment]
@dan-compton Thanks for the report. It seems to be a bug in desugaring. Something is preventing `$` from being desugared properly in this example. I'm working on it.

@seh
> However, my attempts thus far to construct a program that has such a top-level function that's addressable by `$` fail.

This is correct. The expression `$` always refers to the outermost _object_, and objects in jsonnet are not callable, so`$` is never callable. Evaluation of `$(A)` will always fail.

Re:
```
jsonnet eval --tla-code a=1 --exec 'function(a) local z = $; {x: a }'       
STATIC ERROR: <cmdline>:1:23: No top-level object found.
```

This is correct. Top-level object means "the outermost object in which `$` is _lexically_ contained. You can think of it as implicit `local $ = { ... }; $` for each object literal which is not _lexically_ contained in another object literal. 

As a matter of fact you get the same result without tla and function part, it doesn't change anything:
```
jsonnet/jsonnet eval --exec 'local z = $; {x: a }'            
<cmdline>:1:11-12 No top-level object found.
```

However you can do things like this:
```
./jsonnet/jsonnet --tla-code val=5 -e 'function(val) { x: val, y: $.x }'
{
   "x": 5,
   "y": 5
}
```

**Comment by seh** [comment]
Thank you, @sbarzowski. Even for such a seemingly simple language, there is always more to learn.

**Comment by dan-compton** [comment]
Thanks for the explanation @sbarzowski.  Also, if you get a chance, could you take a quick peek at https://groups.google.com/forum/#!topic/jsonnet/SFjTwXgZEr0 ?
