### ISSUE TITLE
"Desugaring desugared object" crash on input that used to work fine

### ISSUE THREAD

**Issue by seh** [google/go-jsonnet#289]
# Observation

Using either the C++ Jsonnet version 0.12.1 or the Go version up until commit 181c86d8157c7de54d052305b318be18b34d27d0, the _jsonnet_ command evaluates my input and manifests the result without error. In commit 33b6dcfa531556502e226c24090622fb3016ff68 (which came in as #263) and later commits all the way to the current head (3ad064e6268b86fd15826a02764d310860173796), _jsonnet_ fails with the following error:
```
INTERNAL ERROR: (CRASH) Desugaring desugared object
goroutine 1 [running]:
runtime/debug.Stack(0xc000708e80, 0x1154480, 0x11e0c70)
	/usr/local/Cellar/go/1.12.6/libexec/src/runtime/debug/stack.go:24 +0x9d
github.com/google/go-jsonnet.(*VM).evaluateSnippet.func1(0xc000717ce0)
	/Users/seh/src/go-jsonnet/vm.go:129 +0x60
panic(0x1154480, 0x11e0c70)
	/usr/local/Cellar/go/1.12.6/libexec/src/runtime/panic.go:522 +0x1b5
github.com/google/go-jsonnet.desugar(0xc0000c1440, 0x0, 0x0, 0x0)
	/Users/seh/src/go-jsonnet/desugarer.go:541 +0x8db
```
The full trace is here:
<details>

```
INTERNAL ERROR: (CRASH) Desugaring desugared object
goroutine 1 [running]:
runtime/debug.Stack(0xc000708e80, 0x1154480, 0x11e0c70)
	/usr/local/Cellar/go/1.12.6/libexec/src/runtime/debug/stack.go:24 +0x9d
github.com/google/go-jsonnet.(*VM).evaluateSnippet.func1(0xc000717ce0)
	/Users/seh/src/go-jsonnet/vm.go:129 +0x60
panic(0x1154480, 0x11e0c70)
	/usr/local/Cellar/go/1.12.6/libexec/src/runtime/panic.go:522 +0x1b5
github.com/google/go-jsonnet.desugar(0xc0000c1440, 0x0, 0x0, 0x0)
	/Users/seh/src/go-jsonnet/desugarer.go:541 +0x8db
github.com/google/go-jsonnet.desugar(0xc00000c030, 0x0, 0x0, 0x0)
	/Users/seh/src/go-jsonnet/desugarer.go:358 +0xe3c
github.com/google/go-jsonnet.desugar(0xc0004f8c70, 0x0, 0x11e6120, 0xc0002de320)
	/Users/seh/src/go-jsonnet/desugarer.go:328 +0x1c54
github.com/google/go-jsonnet.desugar(0xc0004f8c70, 0x0, 0x0, 0x0)
	/Users/seh/src/go-jsonnet/desugarer.go:370 +0x24b8
github.com/google/go-jsonnet.desugar(0xc0004f9958, 0x0, 0x3, 0x158b7c0)
	/Users/seh/src/go-jsonnet/desugarer.go:405 +0x159f
github.com/google/go-jsonnet.desugar(0xc0005023d8, 0x0, 0x3, 0x158b7c0)
	/Users/seh/src/go-jsonnet/desugarer.go:401 +0x156e
github.com/google/go-jsonnet.desugar(0xc000502ed8, 0x0, 0x3, 0x158b7c0)
	/Users/seh/src/go-jsonnet/desugarer.go:401 +0x156e
github.com/google/go-jsonnet.desugar(0xc000503bd8, 0x0, 0x3, 0x158b7c0)
	/Users/seh/src/go-jsonnet/desugarer.go:401 +0x156e
github.com/google/go-jsonnet.desugar(0xc000506958, 0x0, 0x3, 0x158b7c0)
	/Users/seh/src/go-jsonnet/desugarer.go:401 +0x156e
github.com/google/go-jsonnet.desugar(0xc000507c58, 0x0, 0x3, 0x158b7c0)
	/Users/seh/src/go-jsonnet/desugarer.go:401 +0x156e
github.com/google/go-jsonnet.desugar(0xc00050c4d8, 0x0, 0x3, 0x158b7c0)
	/Users/seh/src/go-jsonnet/desugarer.go:401 +0x156e
github.com/google/go-jsonnet.desugar(0xc00050d4d8, 0x0, 0x3, 0x158b7c0)
	/Users/seh/src/go-jsonnet/desugarer.go:401 +0x156e
github.com/google/go-jsonnet.desugar(0xc00050e0d8, 0x0, 0x3, 0x158b7c0)
	/Users/seh/src/go-jsonnet/desugarer.go:401 +0x156e
github.com/google/go-jsonnet.desugar(0xc00024be58, 0x0, 0x3, 0x158b7c0)
	/Users/seh/src/go-jsonnet/desugarer.go:401 +0x156e
github.com/google/go-jsonnet.desugar(0xc00024bef0, 0x0, 0x1, 0x0)
	/Users/seh/src/go-jsonnet/desugarer.go:401 +0x156e
github.com/google/go-jsonnet.desugar(0xc00024bf70, 0x0, 0x1, 0x0)
	/Users/seh/src/go-jsonnet/desugarer.go:508 +0xab6
github.com/google/go-jsonnet.desugar(0xc00024bff0, 0x0, 0x1, 0x0)
	/Users/seh/src/go-jsonnet/desugarer.go:508 +0xab6
github.com/google/go-jsonnet.desugar(0xc00024c070, 0x0, 0x1, 0x0)
	/Users/seh/src/go-jsonnet/desugarer.go:508 +0xab6
github.com/google/go-jsonnet.desugar(0xc00024c0f0, 0x0, 0x1, 0x0)
	/Users/seh/src/go-jsonnet/desugarer.go:508 +0xab6
github.com/google/go-jsonnet.desugar(0xc00024c170, 0x0, 0x1, 0x0)
	/Users/seh/src/go-jsonnet/desugarer.go:508 +0xab6
github.com/google/go-jsonnet.desugar(0xc00024c1f0, 0x0, 0x1, 0x0)
	/Users/seh/src/go-jsonnet/desugarer.go:508 +0xab6
github.com/google/go-jsonnet.desugar(0xc00024c270, 0x0, 0x1, 0x0)
	/Users/seh/src/go-jsonnet/desugarer.go:508 +0xab6
github.com/google/go-jsonnet.desugar(0xc00024c2f0, 0x0, 0x1, 0x0)
	/Users/seh/src/go-jsonnet/desugarer.go:508 +0xab6
github.com/google/go-jsonnet.desugar(0xc00024c370, 0x0, 0x0, 0x0)
	/Users/seh/src/go-jsonnet/desugarer.go:508 +0xab6
github.com/google/go-jsonnet.desugar(0xc00024c3f0, 0x0, 0x1, 0x0)
	/Users/seh/src/go-jsonnet/desugarer.go:405 +0x159f
github.com/google/go-jsonnet.desugar(0xc00024c470, 0x0, 0x1, 0x0)
	/Users/seh/src/go-jsonnet/desugarer.go:508 +0xab6
github.com/google/go-jsonnet.desugar(0xc00024c4f0, 0x0, 0x1, 0x0)
	/Users/seh/src/go-jsonnet/desugarer.go:508 +0xab6
github.com/google/go-jsonnet.desugar(0xc000240460, 0x0, 0x0, 0x0)
	/Users/seh/src/go-jsonnet/desugarer.go:508 +0xab6
github.com/google/go-jsonnet.desugar(0xc00024c570, 0x0, 0x0, 0x0)
	/Users/seh/src/go-jsonnet/desugarer.go:328 +0x1c54
github.com/google/go-jsonnet.desugar(0xc00024c5f0, 0x0, 0x1, 0x0)
	/Users/seh/src/go-jsonnet/desugarer.go:405 +0x159f
github.com/google/go-jsonnet.desugar(0xc00024c670, 0x0, 0x1, 0x0)
	/Users/seh/src/go-jsonnet/desugarer.go:508 +0xab6
github.com/google/go-jsonnet.desugar(0xc00024c6f0, 0x0, 0x1, 0x0)
	/Users/seh/src/go-jsonnet/desugarer.go:508 +0xab6
github.com/google/go-jsonnet.desugar(0xc00024c770, 0x0, 0x1, 0x0)
	/Users/seh/src/go-jsonnet/desugarer.go:508 +0xab6
github.com/google/go-jsonnet.desugar(0xc00024c7f0, 0x0, 0x1, 0x0)
	/Users/seh/src/go-jsonnet/desugarer.go:508 +0xab6
github.com/google/go-jsonnet.desugar(0xc00024c870, 0x0, 0x1, 0x0)
	/Users/seh/src/go-jsonnet/desugarer.go:508 +0xab6
github.com/google/go-jsonnet.desugar(0xc00024c8f0, 0x0, 0x1, 0x0)
	/Users/seh/src/go-jsonnet/desugarer.go:508 +0xab6
github.com/google/go-jsonnet.desugar(0xc00024c970, 0x0, 0x1, 0x0)
	/Users/seh/src/go-jsonnet/desugarer.go:508 +0xab6
github.com/google/go-jsonnet.desugar(0xc000515e90, 0x0, 0xc0007116f0, 0x1042ee2)
	/Users/seh/src/go-jsonnet/desugarer.go:508 +0xab6
github.com/google/go-jsonnet.desugar(0xc00024c9f0, 0x0, 0x1, 0x0)
	/Users/seh/src/go-jsonnet/desugarer.go:447 +0x275b
github.com/google/go-jsonnet.desugar(0xc00024ca70, 0x0, 0x1, 0x0)
	/Users/seh/src/go-jsonnet/desugarer.go:508 +0xab6
github.com/google/go-jsonnet.desugar(0xc00024caf0, 0x0, 0x1, 0x0)
	/Users/seh/src/go-jsonnet/desugarer.go:508 +0xab6
github.com/google/go-jsonnet.desugar(0xc00024cb70, 0x0, 0x1, 0x0)
	/Users/seh/src/go-jsonnet/desugarer.go:508 +0xab6
github.com/google/go-jsonnet.desugar(0xc00024cbf0, 0x0, 0x1, 0x0)
	/Users/seh/src/go-jsonnet/desugarer.go:508 +0xab6
github.com/google/go-jsonnet.desugar(0xc00024cc70, 0x0, 0x1, 0x0)
	/Users/seh/src/go-jsonnet/desugarer.go:508 +0xab6
github.com/google/go-jsonnet.desugar(0xc00024ccf0, 0x0, 0x1, 0x0)
	/Users/seh/src/go-jsonnet/desugarer.go:508 +0xab6
github.com/google/go-jsonnet.desugar(0xc0000a35b0, 0x0, 0xc0001be000, 0x9a45)
	/Users/seh/src/go-jsonnet/desugarer.go:508 +0xab6
github.com/google/go-jsonnet.desugarFile(...)
	/Users/seh/src/go-jsonnet/desugarer.go:587
github.com/google/go-jsonnet.snippetToAST(0xc0000df580, 0x36, 0xc0001be000, 0x9a45, 0x0, 0x0, 0x0, 0x36)
	/Users/seh/src/go-jsonnet/vm.go:207 +0xb0
github.com/google/go-jsonnet.codeToPV(0xc0000e60a0, 0xc0000df580, 0x36, 0xc0001be000, 0x9a45, 0xc0000a3500)
	/Users/seh/src/go-jsonnet/imports.go:110 +0x59
github.com/google/go-jsonnet.(*ImportCache).ImportCode(0xc0000f8c00, 0xc0000f6370, 0x47, 0xc0000dea40, 0x36, 0xc0000e60a0, 0xc00009e300, 0xc0000a27d0, 0x116ab00, 0xc0000c0801, ...)
	/Users/seh/src/go-jsonnet/imports.go:136 +0x195
github.com/google/go-jsonnet.(*interpreter).evaluate(0xc0000e60a0, 0x11e63e0, 0xc00009e300, 0x1, 0x0, 0x75bcd15, 0xc0001abb00, 0xc0001abb00)
	/Users/seh/src/go-jsonnet/interpreter.go:465 +0x340a
github.com/google/go-jsonnet.(*interpreter).EvalInCleanEnv(0xc0000e60a0, 0xc0001a45b0, 0xc0000a27f0, 0xc0000cf480, 0x11e63e0, 0xc00009e300, 0x158ae00, 0x0, 0x0, 0x3, ...)
	/Users/seh/src/go-jsonnet/interpreter.go:916 +0xc7
github.com/google/go-jsonnet.(*cachedThunk).getValue(0xc0000c0a40, 0xc0000e60a0, 0xc0001a45b0, 0xc0000a27f0, 0x10, 0x40, 0x40, 0x1177c60)
	/Users/seh/src/go-jsonnet/thunks.go:76 +0x8c
github.com/google/go-jsonnet.(*interpreter).evaluate(0xc0000e60a0, 0x11e67e0, 0xc0001a45b0, 0x0, 0xc000338260, 0x100b9d8, 0x40, 0x1177c60)
	/Users/seh/src/go-jsonnet/interpreter.go:508 +0x11d0
github.com/google/go-jsonnet.(*interpreter).evaluate(0xc0000e60a0, 0x11e6120, 0xc0000c46e0, 0x1, 0xc0000cb2a0, 0x75bcd15, 0xc0001abce0, 0x1177c60)
	/Users/seh/src/go-jsonnet/interpreter.go:540 +0x2cef
github.com/google/go-jsonnet.(*interpreter).evaluate(0xc0000e60a0, 0x11e65e0, 0xc0000e3f80, 0x1, 0xc0000cb0f8, 0x75bcd15, 0xc0001abc80, 0x0)
	/Users/seh/src/go-jsonnet/interpreter.go:497 +0x427
github.com/google/go-jsonnet.(*interpreter).evaluate(0xc0000e60a0, 0x11e65e0, 0xc0001a8000, 0x1, 0xc0000caf50, 0x75bcd15, 0xc0001abc20, 0xc00014bbc0)
	/Users/seh/src/go-jsonnet/interpreter.go:497 +0x427
github.com/google/go-jsonnet.(*interpreter).evaluate(0xc0000e60a0, 0x11e65e0, 0xc0001a8080, 0x1, 0x0, 0x75bcd15, 0xc0001abbc0, 0x0)
	/Users/seh/src/go-jsonnet/interpreter.go:497 +0x427
github.com/google/go-jsonnet.(*interpreter).EvalInCleanEnv(0xc0000e60a0, 0xc000147540, 0xc0000ef760, 0xc0000cf4c0, 0x11e65e0, 0xc0001a8080, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/seh/src/go-jsonnet/interpreter.go:916 +0xc7
github.com/google/go-jsonnet.(*closure).EvalCall(0xc00009e600, 0xc00009c018, 0x1, 0x1, 0x158aed0, 0x0, 0x0, 0x0, 0xc0000e60a0, 0xc000147540, ...)
	/Users/seh/src/go-jsonnet/thunks.go:204 +0x4bf
github.com/google/go-jsonnet.(*valueFunction).call(0xc0000a3560, 0xc0000e60a0, 0xc000147540, 0xc0000ef760, 0xc00009c018, 0x1, 0x1, 0x158aed0, 0x0, 0x0, ...)
	/Users/seh/src/go-jsonnet/value.go:267 +0x1c5
github.com/google/go-jsonnet.(*interpreter).evaluateTailCall(0xc0000e60a0, 0xc0000a3560, 0xc00009c018, 0x1, 0x1, 0x158aed0, 0x0, 0x0, 0x0, 0x1, ...)
	/Users/seh/src/go-jsonnet/interpreter.go:931 +0xa2
github.com/google/go-jsonnet.(*interpreter).evaluate(0xc0000e60a0, 0x11e6120, 0xc000147540, 0x1, 0x0, 0x75bcd15, 0xc000168540, 0x0)
	/Users/seh/src/go-jsonnet/interpreter.go:563 +0x317e
github.com/google/go-jsonnet.(*interpreter).EvalInCleanEnv(0xc0000e60a0, 0xc000146280, 0x131df10, 0xc0000f9900, 0x11e6120, 0xc000147540, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/seh/src/go-jsonnet/interpreter.go:916 +0xc7
github.com/google/go-jsonnet.(*closure).EvalCall(0xc00009ac60, 0xc000098020, 0x1, 0x1, 0x158aed0, 0x0, 0x0, 0x0, 0xc0000e60a0, 0xc000146280, ...)
	/Users/seh/src/go-jsonnet/thunks.go:204 +0x4bf
github.com/google/go-jsonnet.(*valueFunction).call(0xc0000ef980, 0xc0000e60a0, 0xc000146280, 0x131df10, 0xc000098020, 0x1, 0x1, 0x158aed0, 0x0, 0x0, ...)
	/Users/seh/src/go-jsonnet/value.go:267 +0x1c5
github.com/google/go-jsonnet.(*interpreter).evaluateTailCall(0xc0000e60a0, 0xc0000ef980, 0xc000098020, 0x1, 0x1, 0x158aed0, 0x0, 0x0, 0x0, 0x1, ...)
	/Users/seh/src/go-jsonnet/interpreter.go:931 +0xa2
github.com/google/go-jsonnet.(*interpreter).evaluate(0xc0000e60a0, 0x11e6120, 0xc000146280, 0x1, 0x3, 0xc0000f9580, 0x2, 0x4)
	/Users/seh/src/go-jsonnet/interpreter.go:563 +0x317e
github.com/google/go-jsonnet.(*interpreter).evaluate(0xc0000e60a0, 0x11e65e0, 0xc0000fde80, 0x1, 0x2, 0xc0000ef660, 0x1, 0x2)
	/Users/seh/src/go-jsonnet/interpreter.go:497 +0x427
github.com/google/go-jsonnet.(*interpreter).evaluate(0xc0000e60a0, 0x11e65e0, 0xc0000fdf00, 0x1, 0x0, 0x75bcd15, 0xc00014b920, 0x0)
	/Users/seh/src/go-jsonnet/interpreter.go:497 +0x427
github.com/google/go-jsonnet.(*interpreter).EvalInCleanEnv(0xc0000e60a0, 0xc000080300, 0x0, 0xc00033bab8, 0x11e65e0, 0xc0000fdf00, 0x75bcd00, 0xc00014b920, 0x0, 0x0, ...)
	/Users/seh/src/go-jsonnet/interpreter.go:916 +0xc7
github.com/google/go-jsonnet.evaluateAux(0xc0000e60a0, 0x11e65e0, 0xc0000fdf00, 0xc0000c2930, 0xc0000ce1e0, 0xc0000e60a0, 0x0, 0x0, 0x11e65e0, 0xc0000fdf00)
	/Users/seh/src/go-jsonnet/interpreter.go:1183 +0x15a
github.com/google/go-jsonnet.evaluate(0x11e65e0, 0xc0000fdf00, 0xc0000c2900, 0xc0000c2930, 0xc0000c2960, 0x1f4, 0x11e3f40, 0xc0000ce1e0, 0x0, 0xc0000b5c90, ...)
	/Users/seh/src/go-jsonnet/interpreter.go:1219 +0xc1
github.com/google/go-jsonnet.(*VM).evaluateSnippet(0xc0000a4050, 0x7ffeefbff581, 0x49, 0xc0000ea000, 0x83f, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/seh/src/go-jsonnet/vm.go:138 +0x2e1
github.com/google/go-jsonnet.(*VM).EvaluateSnippet(0xc0000a4050, 0x7ffeefbff581, 0x49, 0xc0000ea000, 0x83f, 0x0, 0x0, 0x0, 0x0)
	/Users/seh/src/go-jsonnet/vm.go:160 +0x69
main.main()
	/Users/seh/src/go-jsonnet/cmd/jsonnet/cmd.go:577 +0xd06

Please report a bug here: https://github.com/google/go-jsonnet/issues
```

</details>

Again, this input evaluates fine with the C++ Jsonnet version as of 0.12.1. The input expands to approximately 5,850 lines of JSON.

Short of supplying all of Jsonnet code—spread across fifteen files or so—what's the right way to figure out what the tests missed here?

# Environment
Go 1.12.6 on macOS (_darwin/amd64_)
Go Jsonnet version output: _Jsonnet commandline interpreter v0.13.0_
C++ Jsonnet version output: _Jsonnet commandline interpreter v0.12.1_ (via Homebrew)

**Comment by sbarzowski** [comment]
Hmmm... after eyeballing your stacktrace and the code for a while, I just started writing random silly examples and I think I found the reason of the crash. Here's a minimal example of problematic code:

./jsonnet -e '[42 for i in [{}]]' 

Object literals in array over which we iterate in a comprehension is a problem.

I think I have a fix.

**Comment by sbarzowski** [comment]
I merged what seems to be the fix. @seh Please let me know if the problem is solved.

**Comment by seh** [comment]
Thank you for the fast fix. I’ll be away from my computer until next Sunday, but as soon as I can test that problematic input again I’ll report the outcome here.

**Comment by seh** [comment]
I confirmed this morning that your #291 fixed the problem for me. Thank you again.

Will this change warrant a release soon?

**Comment by sbarzowski** [comment]
I think we probably should cut the release sooner rather than later, at least just for go-jsonnet (maybe just create a new tag or something). But it's really up to @sparkprime.

**Comment by gotwarlost** [comment]
is there a release for this fix? `qbec` uses `v0.13.0` as a library and it is causing problems for users.

**Comment by sbarzowski** [comment]
Well, not yet. @sparkprime Are we going to cut a release anytime soon?

I suppose most of the friction when doing releases comes from C++ side. I think on Go side making a release boils down to creating a tag (and perhaps sending a message to the mailing group). Perhaps we could allow bugfix releases to be independent between implementations (see also #207, proposition 1). Then we could just cut 0.13.1 right now.

**Comment by sparkprime** [comment]
We have enough changes to do a release on both sides I think?
Is there anything we need to do to bring the 2 sides in sync?
What about that regular expression stuff, it was almost done on the C++ side.

**Comment by sbarzowski** [comment]
> We have enough changes to do a release on both sides I think?
On C++ side I see bindings for C++ bindings for TLAs and various improvements to CMake and shared libraries. That's enough for a release, but less pressing than a critical bug fix and object field caching on a Go side.

> Is there anything we need to do to bring the 2 sides in sync?
I'll update the submodule in a moment, but I don't think we need to do anything in particular. 

> What about that regular expression stuff, it was almost done on the C++ side.
I think that in principle releases shouldn't wait for features (it creates unnecessary pressure on everyone).

**Comment by sparkprime** [comment]
Sure we don't have to wait for RE2, but we don't want to release with it present on one side and not on the other.  So if it doesn't exist yet in go-jsonnet, no problem, otherwise let's just make them the same one way or another.

**Comment by sbarzowski** [comment]
No, it's not there yet in go-jsonnet. BTW I think ideally we would also sync regexp availability with sjsonnet folks to avoid creating incompatible dialects. I'm quite hopeful about it due to https://github.com/google/re2j.

**Comment by sparkprime** [comment]
Synchronising between two different companies is probably more hassle than it's worth :)

OK sounds like we can do a release now.
