### ISSUE TITLE
Include version number and/or git commit hash in crash message

### ISSUE THREAD

**Issue by sbarzowski** [google/go-jsonnet#300]
We have a nice "please report here <link>" message. It would be even better if it included detailed version information, so that we know exactly which version it came from (which for example helps with matching stack trace lines with code).

If we have that automated we can probably also extract the version number from git (rather than needing to remember to change that manually in the code).

**Comment by yiye93** [comment]
INTERNAL ERROR: (CRASH) interface conversion: jsonnet.value is *jsonnet.valueNull, not *jsonnet.valueObject
goroutine 1 [running]:
runtime/debug.Stack(0xc000305538, 0x12bf0e0, 0xc0000859b0)
        /Users/lucky/Documents/software/go_1_11/go/src/runtime/debug/stack.go:24 +0xa7
github.com/google/go-jsonnet.(*VM).evaluateSnippet.func1(0xc000305af0)
        /Users/lucky/Documents/project/go/sivs/src/github.com/google/go-jsonnet/vm.go:137 +0x6e
panic(0x12bf0e0, 0xc0000859b0)
        /Users/lucky/Documents/software/go_1_11/go/src/runtime/panic.go:513 +0x1b9
github.com/google/go-jsonnet.buildStdObject(0xc0000a0140, 0xc00009c780, 0x2d62272c2e9222c8, 0xc0003058e0)
        /Users/lucky/Documents/project/go/sivs/src/github.com/google/go-jsonnet/interpreter.go:1102 +0x405
github.com/google/go-jsonnet.buildInterpreter(0xc000085740, 0xc0000857a0, 0x1f4, 0x1372b40, 0xc00009c6c0, 0x3, 0xc0003059f0, 0x1270ebf)

**Comment by sbarzowski** [comment]
It seems there are features in the newer versions of Go which make it easier:

* https://github.com/jsonnet-bundler/jsonnet-bundler/pull/60
* https://stackoverflow.com/a/54266186/2807880
