### ISSUE TITLE
Cannot build using bazel on Windows 10

### ISSUE THREAD

**Issue by DarioGi** [google/go-jsonnet#354]
I've followed instructions on how to build using bazel:

> git clone github.com/google/go-jsonnet
> cd go-jsonnet
> git submodule init
> git submodule update
> bazel build //cmd/jsonnet

The build command fails with the following:
```
PS C:\Users\test\Documents\jsonnet\go-jsonnet> bazel build //cmd/jsonnet
INFO: Call stack for the definition of repository 'com_github_fatih_color' which is a go_repository (rule definition at C:/users/test/_bazel_test/qrvcx5tl/external/bazel_gazelle/int
ernal/go_repository.bzl:169:17):
 - C:/users/test/_bazel_test/qrvcx5tl/external/google_jsonnet_go/bazel/deps.bzl:22:5
 - C:/users/test/documents/jsonnet/go-jsonnet/WORKSPACE:19:1
ERROR: An error occurred during the fetch of repository 'com_github_fatih_color':
   Traceback (most recent call last):
        File "C:/users/test/_bazel_test/qrvcx5tl/external/bazel_gazelle/internal/go_repository.bzl", line 88
                read_cache_env(ctx, <1 more arguments>)
        File "C:/users/test/_bazel_test/qrvcx5tl/external/bazel_gazelle/internal/go_repository_cache.bzl", line 81, in read_cache_env
                fail(<1 more arguments>)
failed to read cache environment: java.io.IOException: ERROR: src/main/native/windows/process.cc(199): CreateProcessW("cat" C:/users/test/_bazel_test/qrvcx5tl/external/bazel_gazelle
_go_repository_cache/go.env): The system cannot find the file specified.
 (error: 2)
INFO: Call stack for the definition of repository 'org_golang_x_tools' which is a git_repository (rule definition at C:/users/test/_bazel_test/qrvcx5tl/external/bazel_tools/tools/bu
ild_defs/repo/git.bzl:195:18):
 - C:/users/test/_bazel_test/qrvcx5tl/external/io_bazel_rules_go/go/private/repositories.bzl:237:9
 - C:/users/test/_bazel_test/qrvcx5tl/external/io_bazel_rules_go/go/private/repositories.bzl:38:5
 - C:/users/test/_bazel_test/qrvcx5tl/external/google_jsonnet_go/bazel/deps.bzl:13:5
 - C:/users/test/documents/jsonnet/go-jsonnet/WORKSPACE:19:1
INFO: Call stack for the definition of repository 'local_config_cc' which is a cc_autoconf (rule definition at C:/users/test/_bazel_test/qrvcx5tl/external/bazel_tools/tools/cpp/cc_c
onfigure.bzl:143:15):
 - C:/users/test/_bazel_test/qrvcx5tl/external/bazel_tools/tools/cpp/cc_configure.bzl:179:5
 - /DEFAULT.WORKSPACE.SUFFIX:392:1
ERROR: C:/users/test/documents/jsonnet/go-jsonnet/cmd/jsonnet/BUILD.bazel:3:1: //cmd/jsonnet:go_default_library depends on @com_github_fatih_color//:go_default_library in repository @co
m_github_fatih_color which failed to fetch. no such package '@com_github_fatih_color//': Traceback (most recent call last):
        File "C:/users/test/_bazel_test/qrvcx5tl/external/bazel_gazelle/internal/go_repository.bzl", line 88
                read_cache_env(ctx, <1 more arguments>)
        File "C:/users/test/_bazel_test/qrvcx5tl/external/bazel_gazelle/internal/go_repository_cache.bzl", line 81, in read_cache_env
                fail(<1 more arguments>)
failed to read cache environment: java.io.IOException: ERROR: src/main/native/windows/process.cc(199): CreateProcessW("cat" C:/users/test/_bazel_test/qrvcx5tl/external/bazel_gazelle
_go_repository_cache/go.env): The system cannot find the file specified.
 (error: 2)
ERROR: Analysis of target '//cmd/jsonnet:jsonnet' failed; build aborted: no such package '@com_github_fatih_color//': Traceback (most recent call last):
        File "C:/users/test/_bazel_test/qrvcx5tl/external/bazel_gazelle/internal/go_repository.bzl", line 88
                read_cache_env(ctx, <1 more arguments>)
        File "C:/users/test/_bazel_test/qrvcx5tl/external/bazel_gazelle/internal/go_repository_cache.bzl", line 81, in read_cache_env
                fail(<1 more arguments>)
failed to read cache environment: java.io.IOException: ERROR: src/main/native/windows/process.cc(199): CreateProcessW("cat" C:/users/test/_bazel_test/qrvcx5tl/external/bazel_gazelle
_go_repository_cache/go.env): The system cannot find the file specified.
 (error: 2)
INFO: Elapsed time: 1.357s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```
Bazel Version:
```
PS C:\Users\test\Documents\jsonnet\go-jsonnet> bazel version
Build label: 2.0.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 19 12:31:16 2019 (1576758676)
Build timestamp: 1576758676
Build timestamp as int: 157675867
```
It build successfully with "go build" command.
This is potentially an issue with my environment -- any help is greatly appreciated.

**Comment by DarioGi** [comment]
It was a problem with bazel installation, followed the following to resolve it: https://github.com/bazelbuild/rules_go/blob/master/windows.rst

**Comment by schwehr** [comment]
I am seeing the same failure on debian-testing.

At the same level as the `WORKSPACE`, I added an empty `BUILD` file.  And that seemed to fix this issue for me.

```
sudo apt-get install bazel-bootstrap

bazel build //main/...  --record_rule_instantiation_callstack
```

I get this error:

```
INFO: Repository com_github_fatih_color instantiated at:
  /usr/local/google/home/schwehr/src/try-bazel/2/WORKSPACE:21:24: in <toplevel>
  /usr/local/google/home/schwehr/.cache/bazel/_bazel_schwehr/aedefb0f7e04da8e6c61e92118b05b3e/external/jsonnet_go/bazel/deps.bzl:22:18: in jsonnet_go_dependencies
Repository rule go_repository defined at:
  /usr/local/google/home/schwehr/.cache/bazel/_bazel_schwehr/aedefb0f7e04da8e6c61e92118b05b3e/external/bazel_gazelle/internal/go_repository.bzl:169:32: in <toplevel>
ERROR: An error occurred during the fetch of repository 'com_github_fatih_color':
   Traceback (most recent call last):
	File "/usr/local/google/home/schwehr/.cache/bazel/_bazel_schwehr/aedefb0f7e04da8e6c61e92118b05b3e/external/bazel_gazelle/internal/go_repository.bzl", line 29, column 31, in _go_repository_impl
		config_path = ctx.path(ctx.attr.build_config)
Error in path: Unable to load package for //:WORKSPACE: BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /usr/local/google/home/schwehr/src/try-bazel/2
ERROR: /usr/local/google/home/schwehr/.cache/bazel/_bazel_schwehr/aedefb0f7e04da8e6c61e92118b05b3e/external/jsonnet_go/cmd/jsonnet/BUILD.bazel:3:11: @jsonnet_go//cmd/jsonnet:go_default_library depends on @com_github_fatih_color//:go_default_library in repository @com_github_fatih_color which failed to fetch. no such package '@com_github_fatih_color//': Unable to load package for //:WORKSPACE: BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /usr/local/google/home/schwehr/src/try-bazel/2
```
Looking at the error location, I find:

```python
def _go_repository_impl(ctx):
    # Locate and resolve configuration files. Gazelle reads directives and                                                                                         
    # known repositories from these files. Resolving them here forces                                                                                              
    # go_repository rules to be invalidated when they change. Gazelle's cache                                                                                      
    # should NOT be invalidated, so we shouldn't need to download these again.                                                                                     
    # TODO(#549): vcs repositories are not cached and still need to be fetched.                                                                                    
    config_path = None
    if ctx.attr.build_config:
	config_path = ctx.path(ctx.attr.build_config).  # <--- Error occurred here
	for label in _find_macro_file_labels(ctx, ctx.attr.build_config):
            ctx.path(label)
```
