### ISSUE TITLE
go-jsonnet crashes when passing negative index to std.substr

### ISSUE THREAD

**Issue by shoaniki** [google/go-jsonnet#570]
```
$ jsonnet -e 'std.substr("hello", -1, 2)'
INTERNAL ERROR: (CRASH) runtime error: slice bounds out of range [-1:]
goroutine 1 [running]:
runtime/debug.Stack(0x140001deae8, 0x1001d8c40, 0x14000178318)
	/opt/homebrew/Cellar/go/1.15.6/libexec/src/runtime/debug/stack.go:24 +0x88
github.com/google/go-jsonnet.(*VM).evaluateSnippet.func1(0x140001dfca8)
	/private/tmp/go-jsonnet-20201225-66900-1ic2o5q/go-jsonnet-0.17.0/vm.go:173 +0x50
panic(0x1001d8c40, 0x14000178318)
	/opt/homebrew/Cellar/go/1.15.6/libexec/src/runtime/panic.go:965 +0x14c
github.com/google/go-jsonnet.builtinSubstr(0x1400012a120, 0x1001ee5f8, 0x14000114a20, 0x1001ee670, 0x140001244f8, 0x1001ee670, 0x14000124500, 0x1400012a1e0, 0x3, 0x3, ...)
	/private/tmp/go-jsonnet-20201225-66900-1ic2o5q/go-jsonnet-0.17.0/builtins.go:1026 +0xa78
github.com/google/go-jsonnet.(*ternaryBuiltin).evalCall(0x14000106930, 0x140001149f0, 0x3, 0x3, 0x100490e40, 0x0, 0x0, 0x0, 0x1400012a120, 0x3, ...)
	/private/tmp/go-jsonnet-20201225-66900-1ic2o5q/go-jsonnet-0.17.0/builtins.go:1451 +0x190
github.com/google/go-jsonnet.(*valueFunction).call(0x14000105050, 0x1400012a120, 0x140001149f0, 0x3, 0x3, 0x100490e40, 0x0, 0x0, 0x0, 0x100126b98, ...)
	/private/tmp/go-jsonnet-20201225-66900-1ic2o5q/go-jsonnet-0.17.0/value.go:349 +0xd8
github.com/google/go-jsonnet.(*interpreter).evaluateTailCall(0x1400012a120, 0x14000105050, 0x140001149f0, 0x3, 0x3, 0x100490e40, 0x0, 0x0, 0x0, 0x1, ...)
	/private/tmp/go-jsonnet-20201225-66900-1ic2o5q/go-jsonnet-0.17.0/interpreter.go:961 +0x94
github.com/google/go-jsonnet.(*interpreter).evaluate(0x1400012a120, 0x1001f0100, 0x14000172000, 0x1, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/go-jsonnet-20201225-66900-1ic2o5q/go-jsonnet-0.17.0/interpreter.go:587 +0x2a78
github.com/google/go-jsonnet.(*interpreter).EvalInCleanEnv(0x1400012a120, 0x140001dfa58, 0x1001f0100, 0x14000172000, 0x75bcd00, 0x14000107290, 0x0, 0x0, 0x0)
	/private/tmp/go-jsonnet-20201225-66900-1ic2o5q/go-jsonnet-0.17.0/interpreter.go:946 +0x88
github.com/google/go-jsonnet.evaluateAux(0x1400012a120, 0x1001f0100, 0x14000172000, 0x14000106c90, 0x1400012a120, 0x0, 0x0, 0x1a, 0x1001f0100, 0x14000172000)
	/private/tmp/go-jsonnet-20201225-66900-1ic2o5q/go-jsonnet-0.17.0/interpreter.go:1221 +0x128
github.com/google/go-jsonnet.evaluate(0x1001f0100, 0x14000172000, 0x14000106c60, 0x14000106c90, 0x14000106cc0, 0x1f4, 0x14000106e40, 0x14000172000, 0x0, 0x0, ...)
	/private/tmp/go-jsonnet-20201225-66900-1ic2o5q/go-jsonnet-0.17.0/interpreter.go:1260 +0x78
github.com/google/go-jsonnet.(*VM).evaluateSnippet(0x140001dfe50, 0x100154d72, 0x9, 0x0, 0x0, 0x16fdd77db, 0x1a, 0x0, 0x0, 0x0, ...)
	/private/tmp/go-jsonnet-20201225-66900-1ic2o5q/go-jsonnet-0.17.0/vm.go:182 +0x248
github.com/google/go-jsonnet.(*VM).EvaluateAnonymousSnippet(0x140001dfe50, 0x100154d72, 0x9, 0x16fdd77db, 0x1a, 0x0, 0x0, 0x0, 0x107343fff)
	/private/tmp/go-jsonnet-20201225-66900-1ic2o5q/go-jsonnet-0.17.0/vm.go:315 +0x50
main.main()
	/private/tmp/go-jsonnet-20201225-66900-1ic2o5q/go-jsonnet-0.17.0/cmd/jsonnet/cmd.go:461 +0x890

Please report a bug here: https://github.com/google/go-jsonnet/issues
```
C++ jsonnet works fine and gives a sensible error message.

This is not the only case where negative values behave differently in go-jsonnet vs C++ jsonnet, but it's the only one I've found that actually asks me to report the bug :)
(Non-crashy examples are things like the sz parameter of std.makeArray, which C++ jsonnet requires to be positive while go-jsonnet treats negative numbers as 0.)

**Comment by netomi** [comment]
Seems to have been fixed in commit https://github.com/google/go-jsonnet/commit/9e9321f69ae1554de722f2a478f3fbca240f862a

Works as expected with the latest version on master.
