### ISSUE TITLE
Linter panic involving a circular dependency?

### ISSUE THREAD

**Issue by wattdave** [google/go-jsonnet#591]
Here's a reduced example, using jsonnet-lint from 0.18.0:

```a.libsonnet
local b = import './b.libsonnet';

local p = {
  s:: [],

  c: b.callThis(self.s),
};


// Exposed for public use.
{
  p:: p,
}
```
```b.libsonnet
local callThis(fromOther) = fromOther;

// Exposed for public use.
{
  callThis:: callThis,
}
```

Linter behavior:
```
 jsonnet-lint a.libsonnet b.libsonnet                                                                                      [git:master] ✖  
panic: Bug - placeholder for a dependent node cannot be noType

goroutine 1 [running]:
github.com/google/go-jsonnet/linter/internal/types.(*typeGraph).getExprPlaceholder(...)
	/private/tmp/go-jsonnet-20211222-86046-dhqer5/go-jsonnet-0.18.0/linter/internal/types/build_graph.go:26
github.com/google/go-jsonnet/linter/internal/types.calcTP({0x11fe8b8, 0xc0001da180}, 0x0, 0xc0001fb320)
	/private/tmp/go-jsonnet-20211222-86046-dhqer5/go-jsonnet-0.18.0/linter/internal/types/build_graph.go:217 +0x280e
github.com/google/go-jsonnet/linter/internal/types.prepareTPWithPlaceholder({0x11fe8b8, 0xc0001da180}, 0x0, 0xc0001fb320, 0x79)
	/private/tmp/go-jsonnet-20211222-86046-dhqer5/go-jsonnet-0.18.0/linter/internal/types/build_graph.go:86 +0x1ae
github.com/google/go-jsonnet/linter/internal/types.prepareTPWithPlaceholder({0x11feaf8, 0xc0001b0460}, 0x7ff7bfeff875, 0xc0001fb320, 0x77)
	/private/tmp/go-jsonnet-20211222-86046-dhqer5/go-jsonnet-0.18.0/linter/internal/types/build_graph.go:62 +0x5ba
github.com/google/go-jsonnet/linter/internal/types.(*typeGraph).addRoots(0xc0001fb320, 0x11fe8b8, 0xd0)
	/private/tmp/go-jsonnet-20211222-86046-dhqer5/go-jsonnet-0.18.0/linter/internal/types/build_graph.go:96 +0x31a
github.com/google/go-jsonnet/linter/internal/types.Check({0x11feaf8, 0xc0001b0460}, 0x11bbb03, 0x4, 0xc0001c4348, 0x0)
	/private/tmp/go-jsonnet-20211222-86046-dhqer5/go-jsonnet-0.18.0/linter/internal/types/check.go:138 +0xc7
github.com/google/go-jsonnet/linter.lint(0xc0001821e0, {0xc00018e300, 0x2, 0x10a0c54}, 0xc0001a20c0)
	/private/tmp/go-jsonnet-20211222-86046-dhqer5/go-jsonnet-0.18.0/linter/linter.go:87 +0x6d4
github.com/google/go-jsonnet/linter.LintSnippet(0x119fcc0, {0x11fa4e0, 0xc000180010}, {0xc00018e200, 0x2, 0x12fe080})
	/private/tmp/go-jsonnet-20211222-86046-dhqer5/go-jsonnet-0.18.0/linter/linter.go:152 +0x9d
main.main()
	/private/tmp/go-jsonnet-20211222-86046-dhqer5/go-jsonnet-0.18.0/cmd/jsonnet-lint/cmd.go:183 +0x906
```

**Comment by kingindanord** [comment]
I'm experiencing a similar problem. Additionally, the error message doesn't specify which files are causing the issue. As a result, I had to manually run the lint process on various file combinations to find out.

**Comment by augmentmoogi** [comment]
Any update on this? Experiencing this as well.

**Comment by consideRatio** [comment]
@augmentmoogi finding that this happens when multiple files are passed seems like a good indication of what goes wrong - running files individually worked for me as well while running multiple at the same time led to this.

**Comment by consideRatio** [comment]
```
Problems found!
panic: Bug - placeholder for a dependent node cannot be noType
```

### Stacktrace from entrypoint into deeper and deeper function calls.

```
main.main()
	cmd/jsonnet-lint/cmd.go:183 +0x9b2
```

https://github.com/google/go-jsonnet/blob/fed90cd9cd733a87f9fb27cfb32a3e08a7695603/cmd/jsonnet-lint/cmd.go#L183

```
linter.LintSnippet(0xc0000341e0, {0x68d4f8?, 0xc00005a018?}, {0xc000014300?, 0x5db1c0?, 0x68ddb8?})
	linter/linter.go:158 +0x1b3
```

https://github.com/google/go-jsonnet/blob/fed90cd9cd733a87f9fb27cfb32a3e08a7695603/linter/linter.go#L140-L141

```
linter.lint(0xc0000341e0, {0xc0001d7380, 0x4, 0x5fee7f?}, 0xc00098fd70)
	linter/linter.go:87 +0x7c5
```

https://github.com/google/go-jsonnet/blob/fed90cd9cd733a87f9fb27cfb32a3e08a7695603/linter/linter.go#L87

```
linter/internal/types.Check({0x68ecf8, 0xc000082960}, 0xc00098fbd0, 0xc00098f7d0, 0xc00060bb70, 0xc00098f5e8)
	linter/internal/types/check.go:138 +0xd3
```

https://github.com/google/go-jsonnet/blob/fed90cd9cd733a87f9fb27cfb32a3e08a7695603/linter/internal/types/check.go#L138

```
linter/internal/types.(*typeGraph).addRoots(0xc00088e090, 0xc00098fbd0, 0xc00098f7d0)
	linter/internal/types/build_graph.go:96 +0x317
```

https://github.com/google/go-jsonnet/blob/fed90cd9cd733a87f9fb27cfb32a3e08a7695603/linter/internal/types/build_graph.go#L89-L98

Remaining calls are all within the `build_graph` file, and they go like:

`prepareTPWithPlaceholder` -> `prepareTP` -> `prepareTPWithPlaceholder` -> `calcTP` -> `getExprPlaceholder`.

<details><summary>See stack trace for these as well</summary>

```
linter/internal/types.prepareTPWithPlaceholder({0x68e998, 0xc000000a80}, 0xc000473050, 0xc00088e090, 0xa6)
	linter/internal/types/build_graph.go:76 +0x9f6
linter/internal/types.prepareTP({0x68e830, 0xc0001d6480}, 0xc000473050, 0xc00088e090)
	linter/internal/types/build_graph.go:42 +0x1c5
linter/internal/types.prepareTPWithPlaceholder({0x68e830, 0xc0001d6480}, 0xc000473050, 0xc00088e090, 0xb2d)
	linter/internal/types/build_graph.go:86 +0x1f0
linter/internal/types.calcTP({0x68e830?, 0xc0001d6480}, 0xc00098f010?, 0xc00088e090)
	linter/internal/types/build_graph.go:217 +0x2765
linter/internal/types.(*typeGraph).getExprPlaceholder(...)
	linter/internal/types/build_graph.go:26
```

</details>

It ends in `getExprPlaceholder`:

https://github.com/google/go-jsonnet/blob/fed90cd9cd733a87f9fb27cfb32a3e08a7695603/linter/internal/types/build_graph.go#L22-L32

**Comment by vergenzt** [comment]
FYI I'm working around this by using [GNU `parallel`](https://www.gnu.org/software/parallel/) to run `jsonnet-lint` on each file separately, with the following config:

```yaml
- repo: https://github.com/google/go-jsonnet
  rev: v0.20.0
  hooks:
  - id: jsonnet-format
  - id: jsonnet-lint

    # work around https://github.com/google/go-jsonnet/issues/591
    entry: 'parallel jsonnet-lint :::'
```

**Comment by nyoungstudios** [comment]
Thanks for this thread. I also received this error from a circular dependency. So, I added an echo statement before and after the jsonnet-lint command so I could find which file it was occurring in. After resolving the circular dependency, I commented it back out.

```yaml
  - repo: https://github.com/google/go-jsonnet
    rev: v0.22.0
    hooks:
      - id: jsonnet-format
      - id: jsonnet-lint
        entry: >
          bash -c 'for f in "$@"; do echo "before $f"; jsonnet-lint "$f"; echo "after $f"; done' --
```
