### ISSUE TITLE
jsonnetfmt panics on regex string

### ISSUE THREAD

**Issue by harsimranmaan** [google/go-jsonnet#606]
Repro steps:
```
$ brew install go-jsonnet
==> Downloading https://ghcr.io/v2/homebrew/core/go-jsonnet/manifests/0.18.0
...
$ echo "{a : '^/v1/abc-[\w-.]+/xyz/[\w-.]+$'}" > a.jsonnet
$ jsonnetfmt a.jsonnet
panic: Badly formatted string, should have been caught in lexer.

goroutine 1 [running]:
github.com/google/go-jsonnet/internal/formatter.(*EnforceStringStyle).LiteralString(0x140000f8090, {0x1045014b0, 0x140000f8090}, 0x140000ec210, {0x0, 0x0})
	/private/tmp/go-jsonnet-20211221-89224-l130j1/go-jsonnet-0.18.0/internal/formatter/enforce_string_style.go:45 +0x1c8
github.com/google/go-jsonnet/internal/pass.(*Base).Visit(0x140000f8090, {0x1045014b0, 0x140000f8090}, 0x140000fc170, {0x0, 0x0})
	/private/tmp/go-jsonnet-20211221-89224-l130j1/go-jsonnet-0.18.0/internal/pass/pass.go:433 +0x294
github.com/google/go-jsonnet/internal/pass.(*Base).ObjectField(0x140000f8090, {0x1045014b0, 0x140000f8090}, 0x140000fc0f0, {0x0, 0x0})
	/private/tmp/go-jsonnet-20211221-89224-l130j1/go-jsonnet-0.18.0/internal/pass/pass.go:162 +0x10c
github.com/google/go-jsonnet/internal/pass.(*Base).ObjectFields(0x140000f8090, {0x1045014b0, 0x140000f8090}, 0x140000ec330, {0x0, 0x0})
	/private/tmp/go-jsonnet-20211221-89224-l130j1/go-jsonnet-0.18.0/internal/pass/pass.go:193 +0x6c
github.com/google/go-jsonnet/internal/pass.(*Base).Object(0x140000f8090, {0x1045014b0, 0x140000f8090}, 0x140000ec2c0, {0x0, 0x0})
	/private/tmp/go-jsonnet-20211221-89224-l130j1/go-jsonnet-0.18.0/internal/pass/pass.go:333 +0x58
github.com/google/go-jsonnet/internal/pass.(*Base).Visit(0x140000f8090, {0x1045014b0, 0x140000f8090}, 0x1400008e710, {0x0, 0x0})
	/private/tmp/go-jsonnet-20211221-89224-l130j1/go-jsonnet-0.18.0/internal/pass/pass.go:437 +0x824
github.com/google/go-jsonnet/internal/pass.(*Base).File(0x140000f8090, {0x1045014b0, 0x140000f8090}, 0x1400008e710, 0x1400009c138)
	/private/tmp/go-jsonnet-20211221-89224-l130j1/go-jsonnet-0.18.0/internal/pass/pass.go:463 +0x74
github.com/google/go-jsonnet/internal/formatter.visitFile(...)
	/private/tmp/go-jsonnet-20211221-89224-l130j1/go-jsonnet-0.18.0/internal/formatter/jsonnetfmt.go:144
github.com/google/go-jsonnet/internal/formatter.Format({0x16baff883, 0x9}, {0x140000f8000, 0x26}, {0x2, 0x2, 0x1, 0x1, 0x1, 0x0, ...})
	/private/tmp/go-jsonnet-20211221-89224-l130j1/go-jsonnet-0.18.0/internal/formatter/jsonnetfmt.go:183 +0x4ac
main.main()
	/private/tmp/go-jsonnet-20211221-89224-l130j1/go-jsonnet-0.18.0/cmd/jsonnetfmt/cmd.go:289 +0x64c
```
Originally found via https://github.com/splunk/qbec/issues/284

Caused by the `\w` in the string value

**Comment by netomi** [comment]
The suggested fix in the PR for #551 also fixes this issue.

**Comment by johnbartholomew** [comment]
I think this was fixed by #724 (as netomi mentioned above).
